/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jets;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.EventListenerList;

/**
 *
 * @author User
 */
public class AdminGenerateInvoice extends javax.swing.JFrame {
    LinkedList<Invoice> invoiceList = new LinkedList<>();
    LinkedList<String> studentList = new LinkedList<>();
    String url ="jdbc:db2:PMS";
    String id;
    String studentID;
    String amtStr="";
    
    
    /**
     * Creates new form ProgressReport
     */
    public AdminGenerateInvoice() {
        initComponents();
        String date;
        String description;
        String payStatus;
        String admID;
        String temp;
        String amount;
        //String stuID = "1151100653";
        
        contentMainPanel.setVisible(false);
        
        Connection con;
        
        try{
            Class.forName("com.ibm.db2.jcc.DB2Driver");
            con = DriverManager.getConnection(url);
            Statement sql1;
            ResultSet rs;
            
            String s1 ="select * from invoice" ;
            sql1= con.createStatement();
            rs = sql1.executeQuery(s1);
            
            while (rs.next()){
                id = rs.getString("invoice_id");
                amount = rs.getString("amount_to_pay");
                double x = Double.parseDouble(amount);
                date = rs.getString("invoice_date");
                description = rs.getString("invoice_description");
                payStatus = rs.getString("payment_status");
                admID = rs.getString("admin_ID");
                temp = rs.getString("Student_id");
                invoiceList.add(new Invoice(id,x,date,description,payStatus, temp));
//                System.out.println(id + "\t" + amount + "\t" + date + 
//                               "\t" + description + "\t" + payStatus);    
            }
            
            Statement sql2;
            ResultSet rs2;
            String stuID;
            String s2 = "select student_id from student";
            sql2 = con.createStatement();
            rs2 = sql2.executeQuery(s2);
            while (rs2.next()){
                stuID = rs2.getString("student_id");
                studentList.add(stuID);
            }
            
            rs.close();
            sql1.close();
            
            rs2.close();
            sql2.close();
            con.close();
        }catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }        
        
        addInvoice.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProcessCompleteDialog1 = new javax.swing.JDialog();
        ProcessCompletePanel = new javax.swing.JPanel();
        ProcessCompleteOKButton = new javax.swing.JButton();
        ProcessCompleteLabel1 = new javax.swing.JLabel();
        sidepanel2 = new javax.swing.JPanel();
        btnAddInvoice = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        progressReport = new javax.swing.JLabel();
        btn_Back = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        contentMainPanel = new javax.swing.JPanel();
        addInvoice = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        btnAddInvoice1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        ProcessCompleteDialog1.setSize(new java.awt.Dimension(500, 300));

        ProcessCompletePanel.setBackground(new java.awt.Color(255, 255, 255));
        ProcessCompletePanel.setPreferredSize(new java.awt.Dimension(500, 300));

        ProcessCompleteOKButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ProcessCompleteOKButton.setText("OK");
        ProcessCompleteOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessCompleteOKButtonActionPerformed(evt);
            }
        });

        ProcessCompleteLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ProcessCompleteLabel1.setText("Something must have gone wrong!");

        javax.swing.GroupLayout ProcessCompletePanelLayout = new javax.swing.GroupLayout(ProcessCompletePanel);
        ProcessCompletePanel.setLayout(ProcessCompletePanelLayout);
        ProcessCompletePanelLayout.setHorizontalGroup(
            ProcessCompletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProcessCompletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProcessCompletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProcessCompleteLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(ProcessCompletePanelLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(ProcessCompleteOKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ProcessCompletePanelLayout.setVerticalGroup(
            ProcessCompletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProcessCompletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProcessCompleteLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(ProcessCompleteOKButton)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ProcessCompleteDialog1Layout = new javax.swing.GroupLayout(ProcessCompleteDialog1.getContentPane());
        ProcessCompleteDialog1.getContentPane().setLayout(ProcessCompleteDialog1Layout);
        ProcessCompleteDialog1Layout.setHorizontalGroup(
            ProcessCompleteDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProcessCompleteDialog1Layout.createSequentialGroup()
                .addComponent(ProcessCompletePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );
        ProcessCompleteDialog1Layout.setVerticalGroup(
            ProcessCompleteDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProcessCompletePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin- Invoice");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel2.setBackground(new java.awt.Color(60, 100, 255));
        sidepanel2.setPreferredSize(new java.awt.Dimension(340, 720));
        sidepanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddInvoice.setBackground(new java.awt.Color(60, 100, 255));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Invoice_32px_2.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Add Invoice");

        javax.swing.GroupLayout btnAddInvoiceLayout = new javax.swing.GroupLayout(btnAddInvoice);
        btnAddInvoice.setLayout(btnAddInvoiceLayout);
        btnAddInvoiceLayout.setHorizontalGroup(
            btnAddInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAddInvoiceLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        btnAddInvoiceLayout.setVerticalGroup(
            btnAddInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAddInvoiceLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(15, 15, 15))
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepanel2.add(btnAddInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 340, -1));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        sidepanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 280, 10));

        progressReport.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        progressReport.setForeground(new java.awt.Color(255, 255, 255));
        progressReport.setText("Invoice");
        sidepanel2.add(progressReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        btn_Back.setBackground(new java.awt.Color(60, 100, 255));
        btn_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BackMouseClicked(evt);
            }
        });

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Back_Arrow_32px_3.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Back");

        javax.swing.GroupLayout btn_BackLayout = new javax.swing.GroupLayout(btn_Back);
        btn_Back.setLayout(btn_BackLayout);
        btn_BackLayout.setHorizontalGroup(
            btn_BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_BackLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        btn_BackLayout.setVerticalGroup(
            btn_BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_BackLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(15, 15, 15))
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepanel2.add(btn_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, -1));

        getContentPane().add(sidepanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 720));

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setLayout(new java.awt.CardLayout());

        contentMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentMainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        contentPanel.add(contentMainPanel, "card2");

        addInvoice.setBackground(new java.awt.Color(255, 255, 255));
        addInvoice.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Invoice Date             : ");
        addInvoice.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 390, -1));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(102, 102, 102));
        jTextField1.setText("Example: Invoice (words not more than 500)");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        addInvoice.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 520, 50));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Student ID                : ");
        addInvoice.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 370, -1));

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setForeground(new java.awt.Color(102, 102, 102));
        jTextField3.setText("Example: 2017000001");
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        addInvoice.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 520, 50));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Invoice Description : ");
        addInvoice.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 370, -1));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        addInvoice.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 520, 50));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Amount                    : ");
        addInvoice.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 370, -1));

        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setForeground(new java.awt.Color(102, 102, 102));
        jTextField5.setText("Example: 2017-05-20 (Not less than today)");
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });
        addInvoice.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 520, 50));

        btnAddInvoice1.setBackground(new java.awt.Color(240, 240, 240));
        btnAddInvoice1.setPreferredSize(new java.awt.Dimension(155, 155));
        btnAddInvoice1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddInvoice1MouseClicked(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(48, 118, 232));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(48, 118, 232));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Add Invoice");

        javax.swing.GroupLayout btnAddInvoice1Layout = new javax.swing.GroupLayout(btnAddInvoice1);
        btnAddInvoice1.setLayout(btnAddInvoice1Layout);
        btnAddInvoice1Layout.setHorizontalGroup(
            btnAddInvoice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnAddInvoice1Layout.setVerticalGroup(
            btnAddInvoice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAddInvoice1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(29, 29, 29))
        );

        addInvoice.add(btnAddInvoice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 280, 90));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setToolTipText("");
        jTextField2.setBorder(null);
        addInvoice.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, -1));

        contentPanel.add(addInvoice, "card3");

        getContentPane().add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 940, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        boolean idExist = false;
        boolean stuIDCheck = true;
        studentID = jTextField3.getText();
        
        for (int i=0;i<studentList.size();i++){
            if ((studentList.get(i).equals(studentID))){
                idExist = true;
                break;
            }
        }
        
        for (int i=0;i<invoiceList.size();i++){
            if (studentID.equals(invoiceList.get(i).getStuID())){
                stuIDCheck = false;
                break;
            }
        }
        
        if (idExist&&stuIDCheck){
            Connection con;
            try{
                Class.forName("com.ibm.db2.jcc.DB2Driver");
                con = DriverManager.getConnection(url);
                Statement sql1;
                ResultSet rs;

                String s1 ="select sum(subject_cost) as sum from subject s, student x, trimester t "
                        + "where t.subject_id = s.subject_id and t.student_id = x.student_id and "
                        + "x.student_id = '" + studentID +"'";
                sql1= con.createStatement();
                rs = sql1.executeQuery(s1);

                while (rs.next()){
                    amtStr = rs.getString("sum");
                }

                rs.close();
                sql1.close();

                con.close();
            }catch (ClassNotFoundException | SQLException e) {
                System.out.println(e);
            } 
            jTextField4.setText(amtStr);
        }
        else{
            if(!idExist){
                JOptionPane.showMessageDialog(null, "Student ID not exists");
                jTextField3.setText("Example: 2017000001");
            }
            if (!stuIDCheck){
                JOptionPane.showMessageDialog(null, "Invoice created for student");
                jTextField3.setText("Example: 2017000001");
            }
        }
        
    }//GEN-LAST:event_jTextField3FocusLost

    private void btnAddInvoice1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddInvoice1MouseClicked

        String date = jTextField5.getText();
        String desc = jTextField1.getText();
        boolean isCheck = checkDate(date);
        boolean desCheck = checkDes(desc);
        
        if (!isCheck){
            JOptionPane.showMessageDialog(null, "The date should be in YYYY-MM-DD format. Ensure the value is correct");
            jTextField5.setText("");
        }
        
        if (!desCheck){
            JOptionPane.showMessageDialog(null, "Description cannot be more than 500 words");
        }
        String invoiceID;
        if (invoiceList.isEmpty()){
            invoiceID = "INV-000001";
        }
        else{
            invoiceID = generateNewInvoiceID(invoiceList.get(invoiceList.size()-1).getID());
        }
        double amount=0.0; 
        if (jTextField4.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Amount cannot be empty");
        }
        else {
            amount = Double.parseDouble(amtStr);
        }
        
        if (jTextField3.getText().length()>0 && jTextField4.getText().length()>0 && 
                jTextField5.getText().length()>0 && jTextField1.getText().length()>0 && isCheck 
                && desCheck && !jTextField3.getText().equals("Example: 2017000001")){

            String url = "jdbc:db2:PMS";  //database name
            Connection con;
            try
            {
                Class.forName("com.ibm.db2.jcc.DB2Driver");
                con = DriverManager.getConnection(url);
                Statement sql;
                ResultSet rs;

                String input = "insert into INVOICE values (" 
                        + "'" + invoiceID + "'" + ", "
                        + amount + ", "
                        + "'" + date + "'" + ", "
                        + "'" + desc + "'" + ", "
                        + "'NOT PAID'" + ", "
                        + "'" + Jets.UserID + "'" + ", "
                        + "'" + studentID + "')"
                        ;
                sql = con.createStatement();
                sql.executeUpdate(input);
                sql.close();
                con.close();
                jTextField3.setText("");
                jTextField5.setText("");
                jTextField1.setText("");
                jTextField4.setText("");
                jTextField4.setEditable(false);
                jTextField3.setForeground(new java.awt.Color(102,102,102));
                jTextField5.setForeground(new java.awt.Color(102,102,102));
                jTextField1.setForeground(new java.awt.Color(102,102,102));
                jTextField3.setText("Example: 2017000001");
                jTextField5.setText("Example: 2017-05-20 (Not less than today)");
                jTextField1.setText("Example: Invoice (words not more than 500)");
                ProcessCompleteLabel1.setText("Invoice has been added successfully!");
                ProcessCompleteDialog1.setVisible(true);
            }
            catch (ClassNotFoundException | SQLException e)
            {

            }
        }
        else{
            JOptionPane.showMessageDialog(null, "All fields cannot be empty");
            jTextField5.setText("Example: 2017-05-20 (Not less than today)");
            jTextField1.setText("Example: Invoice (words not more than 500)");
        }
    }//GEN-LAST:event_btnAddInvoice1MouseClicked

    private void ProcessCompleteOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessCompleteOKButtonActionPerformed
        ProcessCompleteDialog1.dispose();
    }//GEN-LAST:event_ProcessCompleteOKButtonActionPerformed

    private void btn_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BackMouseClicked
        if (Jets.UserType.equals("STUDENT"))
            new StudentMainMenu().setVisible(true);
        if (Jets.UserType.equals("ADMIN"))
            new AdminMainMenu().setVisible(true);
        if (Jets.UserType.equals("LECTURER"))
            new LecturerMainMenu().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_BackMouseClicked

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
        if (jTextField3.getText().equals("Example: 2017000001"))
            jTextField3.setText("");
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusGained
        if (jTextField5.getText().equals("Example: 2017-05-20 (Not less than today)"))   
            jTextField5.setText("");
    }//GEN-LAST:event_jTextField5FocusGained

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        if (jTextField1.getText().equals("Example: Invoice (words not more than 500)")) 
            jTextField1.setText("");

    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        // TODO add your handling code here:
        if (jTextField5.getText().equals("")){
            jTextField5.setText("Example: 2017-05-20 (Not less than today)");
        }
    }//GEN-LAST:event_jTextField5FocusLost

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        if (jTextField1.getText().equals("")){
            jTextField1.setText("Example: Invoice (words not more than 500)");
        }   
    }//GEN-LAST:event_jTextField1FocusLost
    
    public String generateNewInvoiceID(String lastID){
        String[] splited = lastID.split("-");
        String splitDigit = splited[1];
        int digit = Integer.parseInt(splitDigit);
        String newID = String.format("%0"+6+"d", digit+1);
        return ("INV-"+newID);
    }
    
    public boolean checkDes(String desc){
        boolean check = false;
        if (desc.length()>500){
            return check;
        }
        else{
            return true;
        }
    }
    
    public boolean checkDate(String date){
        date = date.toLowerCase();
        if (date.contains("a")||date.contains("b")||date.contains("c")||date.contains("d")||date.contains("e")||date.contains("f")
                ||date.contains("g")||date.contains("h")||date.contains("i")||date.contains("j")||date.contains("k")||date.contains("l")
                ||date.contains("m")||date.contains("n")||date.contains("o")||date.contains("p")||date.contains("q")||date.contains("r")
                ||date.contains("s")||date.contains("t")||date.contains("u")||date.contains("v")||date.contains("w")||date.contains("x")
                ||date.contains("y")||date.contains("z")||date.contains(".")||date.contains("/")){
            return false;
        }
        if(date.length()>10 || date.length()<10){
            return false;
        }
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate localDate = LocalDate.now();
        String d1 = localDate.format(dtf);
        String[] dt = d1.split("-");
        String y = dt[0];
        String m = dt[1];
        String d = dt[2];
        String[] splited = date.split("-");
        String splitYear = splited[0];
        String splitMonth = splited[1];
        String splitDay = splited[2];
        int currentY = Integer.parseInt(y);
        int currentM = Integer.parseInt(m);
        int currentD = Integer.parseInt(d);
        int targetY = Integer.parseInt(splitYear);
        int targetM = Integer.parseInt(splitMonth);
        int targetD = Integer.parseInt(splitDay);
        if (currentY>targetY){
            return false;
        }
        if ((currentY<targetY)&&(currentM>targetM)){
            return false;
        }
        if ((currentY<targetY)&&(currentM<targetM)&&(currentD>targetD)){
            return false;
        }
        String datePattern = "\\d{4}-\\d{2}-\\d{2}";
        return ((date.matches(datePattern))&&(checkMonthAndDay(Integer.parseInt(splitYear),Integer.parseInt(splitMonth),Integer.parseInt(splitDay))));
          
    }
    
    public boolean checkMonthAndDay(int year, int month, int day){
        int month31[] = {1,3,5,7,8,10,12};
        int month30[] = {4,6,9,11};
        int month28[] = {2};
        double yr = (double)year;
        boolean checked = true;
        if (contains(month31, month)){
            if (day>31){
                checked = false;
            }
        }
        if (contains(month30, month)){
            if (day>30){
                checked = false;
            }
        }
        //System.out.println(yr%4);
        if (contains(month28, month)){
            if (yr%4 == 0){
                if (day>29){
                    System.out.println(yr%4);
                    checked = false;
                }
            }
            else{
                if (day>28){
                    checked = false;
                }
            }
        }
        return checked;
    }
    
    public boolean contains(final int[] array, final int v) {
        for (final int e : array)
            if (e == v)
                return true;
        return false;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgressReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgressReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgressReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgressReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminGenerateInvoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog ProcessCompleteDialog1;
    private javax.swing.JLabel ProcessCompleteLabel1;
    private javax.swing.JButton ProcessCompleteOKButton;
    private javax.swing.JPanel ProcessCompletePanel;
    private javax.swing.JPanel addInvoice;
    private javax.swing.JPanel btnAddInvoice;
    private javax.swing.JPanel btnAddInvoice1;
    private javax.swing.JPanel btn_Back;
    private javax.swing.JPanel contentMainPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel progressReport;
    private javax.swing.JPanel sidepanel2;
    // End of variables declaration//GEN-END:variables
}
