/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jets;
import java.sql.*;
import java.util.Calendar;
import java.util.LinkedList;
import javax.swing.JOptionPane;
/**
 *
 * @author FOOCK
 */
public class ProfileManagement extends javax.swing.JFrame {
    /**
     * Creates new form Profile2
     */
    String Name;
    String Gender = null;
    String Race = null;
    String Address = null;
    String Contact = null;
    String Email = null;
    String url = "jdbc:db2:PMS"; //database name
    Connection con;
    int noStudent; // for now becuase database have dummy data, suppose to be 0
    int noLecturer; // for now becuase database have dummy data, suppose to be 0
    int noAdmin; // for now becuase database have dummy data, suppose to be 0
    
    public ProfileManagement() {
        initComponents();
        if(!(Jets.UserType).equals("ADMIN"))
        {
            AddProfile.setVisible(false);
        }
        else 
        {
            
            try {
		Class.forName("com.ibm.db2.jcc.DB2Driver");
		con = DriverManager.getConnection(url);
		Statement sql1;
		ResultSet rs;
		String s1 = "SELECT COURSE_ID FROM COURSE";
                sql1 = con.createStatement();
                rs = sql1.executeQuery(s1);
		while (rs.next ()) {
                    Coursebox.addItem(rs.getString(1));      
		}
                rs.close();
		sql1.close();
		con.close();
            } //end try	
            catch (ClassNotFoundException | SQLException e) {
                    System.out.println(e);
            }
            
        }
        try {
		Class.forName("com.ibm.db2.jcc.DB2Driver");
		con = DriverManager.getConnection(url);
		Statement sql1;
		ResultSet rs;
		String s1 = "SELECT RECORD FROM COUNTER WHERE COUNTER_ID = 'STUDENT'";
                String s2 = "SELECT RECORD FROM COUNTER WHERE COUNTER_ID = 'LECTURER'";
                String s3 = "SELECT RECORD FROM COUNTER WHERE COUNTER_ID = 'ADMIN'";
                sql1 = con.createStatement();
                rs = sql1.executeQuery(s1);
		while (rs.next ()) {
                    noStudent = rs.getInt(1);      
		}
                rs = sql1.executeQuery(s2);
		while (rs.next ()) {
                    noLecturer = rs.getInt(1);
		}
                rs = sql1.executeQuery(s3);
		while (rs.next ()) {
                    noAdmin = rs.getInt(1);
		}
                rs.close();
		sql1.close();
		con.close();
            } //end try	
            catch (ClassNotFoundException | SQLException e) {
                    System.out.println(e);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ViewProfile = new javax.swing.JButton();
        EditProfile = new javax.swing.JButton();
        AddProfile = new javax.swing.JButton();

        jLayeredPane2 = new javax.swing.JLayeredPane();
        blank = new javax.swing.JPanel();
        viewprofile = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        namelabel = new javax.swing.JLabel();
        genderlabel = new javax.swing.JLabel();
        racelabel = new javax.swing.JLabel();
        contactlabel = new javax.swing.JLabel();
        emaillabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addresslabel = new javax.swing.JTextArea();
        editprofile = new javax.swing.JPanel();
        editprofile.setVisible(false);
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        enamelabel = new javax.swing.JLabel();
        egenderlabel = new javax.swing.JLabel();
        eracelabel = new javax.swing.JLabel();
        addressfield = new javax.swing.JTextField();
        contactfield = new javax.swing.JTextField();
        emailfield = new javax.swing.JTextField();
        econfirm = new javax.swing.JButton();
        addprofile = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        aname = new javax.swing.JTextField();
        aaddressfield = new javax.swing.JTextField();
        acontactfield = new javax.swing.JTextField();
        aemailfield = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        aconfirm = new javax.swing.JButton();
        jLabel66 = new javax.swing.JLabel();
        Typebox = new javax.swing.JComboBox<>();
        Coursebox = new javax.swing.JComboBox<>();
        Genderbox = new javax.swing.JComboBox<>();
        Racebox = new javax.swing.JComboBox<>();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        Supervisorbox = new javax.swing.JComboBox<>();
        jLabel69 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User - Profile Management");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(60, 100, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(340, 720));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Profile Management");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-Back To-64.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel17MousePressed(evt);
            }
        });

        ViewProfile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ViewProfile.setForeground(new java.awt.Color(255, 255, 255));
        ViewProfile.setText("View Profile");
        ViewProfile.setAlignmentY(0.0F);
        ViewProfile.setContentAreaFilled(false);
        ViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProfileActionPerformed(evt);
            }
        });

        EditProfile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EditProfile.setForeground(new java.awt.Color(255, 255, 255));
        EditProfile.setText("Edit Profile");
        EditProfile.setToolTipText("");
        EditProfile.setAlignmentY(0.0F);
        EditProfile.setContentAreaFilled(false);
        EditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfileActionPerformed(evt);
            }
        });

        AddProfile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AddProfile.setForeground(new java.awt.Color(255, 255, 255));
        AddProfile.setText("Add Profile");
        AddProfile.setContentAreaFilled(false);
        AddProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ViewProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EditProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(501, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLayeredPane2.setLayout(new java.awt.CardLayout());

        blank.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout blankLayout = new javax.swing.GroupLayout(blank);
        blank.setLayout(blankLayout);
        blankLayout.setHorizontalGroup(
            blankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        blankLayout.setVerticalGroup(
            blankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        jLayeredPane2.add(blank, "card5");

        viewprofile.setBackground(new java.awt.Color(255, 255, 255));
        viewprofile.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("View Profile");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Gender:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Race:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Address:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Contact:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Email:");

        namelabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        namelabel.setText("FOO CHUAN KANG");

        genderlabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        genderlabel.setText("MALE");

        racelabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        racelabel.setText("CHINESE");
        racelabel.setAlignmentY(0.0F);

        contactlabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        contactlabel.setText("012-3456789");

        emaillabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        emaillabel.setText("mail@mail.edu.my");

        addresslabel.setEditable(false);
        addresslabel.setColumns(20);
        addresslabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        addresslabel.setRows(5);
        jScrollPane1.setViewportView(addresslabel);

        javax.swing.GroupLayout viewprofileLayout = new javax.swing.GroupLayout(viewprofile);
        viewprofile.setLayout(viewprofileLayout);
        viewprofileLayout.setHorizontalGroup(
            viewprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewprofileLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(viewprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewprofileLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewprofileLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emaillabel, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewprofileLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contactlabel))
                    .addComponent(jLabel1)
                    .addGroup(viewprofileLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namelabel))
                    .addGroup(viewprofileLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genderlabel))
                    .addGroup(viewprofileLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(racelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        viewprofileLayout.setVerticalGroup(
            viewprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewprofileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(viewprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namelabel))
                .addGap(41, 41, 41)
                .addGroup(viewprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(genderlabel))
                .addGap(43, 43, 43)
                .addGroup(viewprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(racelabel))
                .addGap(41, 41, 41)
                .addGroup(viewprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(viewprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(contactlabel))
                .addGap(41, 41, 41)
                .addGroup(viewprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(emaillabel))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jLayeredPane2.add(viewprofile, "card3");

        editprofile.setBackground(new java.awt.Color(255, 255, 255));
        editprofile.setName(""); // NOI18N

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel33.setText("Edit Profile");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel34.setText("Name:");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel35.setText("Gender:");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel36.setText("Race:");

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel37.setText("Address:");

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel38.setText("Contact:");

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel39.setText("Email:");

        enamelabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        enamelabel.setText("FOO CHUAN KANG");

        egenderlabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        egenderlabel.setText("MALE");

        eracelabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        eracelabel.setText("CHINESE");

        addressfield.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        addressfield.setForeground(new java.awt.Color(102, 102, 102));
        addressfield.setText("Not more than 100 characters");
        addressfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressfieldFocusLost(evt);
            }
        });

        contactfield.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        contactfield.setForeground(new java.awt.Color(120, 120, 120));
        contactfield.setText("Example: 012-3456789");
        contactfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contactfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contactfieldFocusLost(evt);
            }
        });

        emailfield.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        emailfield.setForeground(new java.awt.Color(120, 120, 120));
        emailfield.setText("Example: mail@mail.com");
        emailfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailfieldFocusLost(evt);
            }
        });

        econfirm.setText("Confirm");
        econfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                econfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editprofileLayout = new javax.swing.GroupLayout(editprofile);
        editprofile.setLayout(editprofileLayout);
        editprofileLayout.setHorizontalGroup(
            editprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editprofileLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(editprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(econfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(editprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel33)
                        .addGroup(editprofileLayout.createSequentialGroup()
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(enamelabel))
                        .addGroup(editprofileLayout.createSequentialGroup()
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(egenderlabel))
                        .addGroup(editprofileLayout.createSequentialGroup()
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(eracelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(editprofileLayout.createSequentialGroup()
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(emailfield, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(editprofileLayout.createSequentialGroup()
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(contactfield, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(editprofileLayout.createSequentialGroup()
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(addressfield, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        editprofileLayout.setVerticalGroup(
            editprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editprofileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addGap(36, 36, 36)
                .addGroup(editprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(enamelabel))
                .addGap(41, 41, 41)
                .addGroup(editprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(egenderlabel))
                .addGap(43, 43, 43)
                .addGroup(editprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(eracelabel))
                .addGap(41, 41, 41)
                .addGroup(editprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(addressfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(editprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(contactfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(editprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addComponent(emailfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(econfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jLayeredPane2.add(editprofile, "card3");

        addprofile.setBackground(new java.awt.Color(255, 255, 255));
        addprofile.setName(""); // NOI18N

        jLabel58.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel58.setText("Add Profile");

        jLabel59.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel59.setText("Name:");

        jLabel60.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel60.setText("Gender:");

        jLabel61.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel61.setText("Race:");

        jLabel62.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel62.setText("Address:");

        jLabel63.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel63.setText("Contact:");

        jLabel64.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel64.setText("Email:");

        aname.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        aname.setForeground(new java.awt.Color(120, 120, 120));
        aname.setText("Not more than 30 characters");
        aname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                anameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                anameFocusLost(evt);
            }
        });

        aaddressfield.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        aaddressfield.setForeground(new java.awt.Color(120, 120, 120));
        aaddressfield.setText("Not more than 100 characters");
        aaddressfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                aaddressfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                aaddressfieldFocusLost(evt);
            }
        });

        acontactfield.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        acontactfield.setForeground(new java.awt.Color(120, 120, 120));
        acontactfield.setText("Example: 012-3456789");
        acontactfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                acontactfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                acontactfieldFocusLost(evt);
            }
        });

        aemailfield.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        aemailfield.setForeground(new java.awt.Color(120, 120, 120));
        aemailfield.setText("Example: mail@mail.com");
        aemailfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                aemailfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                aemailfieldFocusLost(evt);
            }
        });

        jLabel65.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel65.setText("Type:");

        aconfirm.setText("Confirm");
        aconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aconfirmActionPerformed(evt);
            }
        });

        jLabel66.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel66.setText("Course:");

        Typebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "LECTURER", "STUDENT" }));
        Typebox.setSelectedItem("fsfsdf");

        Coursebox.setSelectedItem("fsfsdf");
        Coursebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseboxActionPerformed(evt);
            }
        });

        Genderbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE" }));
        Genderbox.setSelectedItem("fsfsdf");

        Racebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALAY", "CHINESE", "INDIAN", "OTHER" }));
        Racebox.setSelectedItem("fsfsdf");

        jLabel67.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel67.setText("Not applicable for Lecturer and Admin");

        jLabel68.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel68.setText("Supervisor");

        Supervisorbox.setSelectedItem("fsfsdf");
        Supervisorbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupervisorboxActionPerformed(evt);
            }
        });

        jLabel69.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel69.setText("Not applicable for Lecturer and Admin");

        javax.swing.GroupLayout addprofileLayout = new javax.swing.GroupLayout(addprofile);
        addprofile.setLayout(addprofileLayout);
        addprofileLayout.setHorizontalGroup(
            addprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addprofileLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(addprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel58)
                            .addGroup(addprofileLayout.createSequentialGroup()
                                .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(aaddressfield, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addprofileLayout.createSequentialGroup()
                                .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(aemailfield))
                            .addGroup(addprofileLayout.createSequentialGroup()
                                .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(acontactfield, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addprofileLayout.createSequentialGroup()
                                .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(aname, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addprofileLayout.createSequentialGroup()
                                .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Racebox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(addprofileLayout.createSequentialGroup()
                                .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Genderbox, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(addprofileLayout.createSequentialGroup()
                            .addGroup(addprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addprofileLayout.createSequentialGroup()
                                    .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Coursebox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(addprofileLayout.createSequentialGroup()
                                    .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Typebox, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel67))
                        .addGroup(addprofileLayout.createSequentialGroup()
                            .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Supervisorbox, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel69))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        addprofileLayout.setVerticalGroup(
            addprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addprofileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel58)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel65)
                    .addComponent(Typebox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(addprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Coursebox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel67))
                    .addComponent(jLabel66))
                .addGap(30, 30, 30)
                .addGroup(addprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(aname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(addprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60)
                    .addComponent(Genderbox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(addprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(Racebox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(addprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62)
                    .addComponent(aaddressfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(addprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel63)
                    .addComponent(acontactfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(addprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel64)
                    .addComponent(aemailfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(addprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel68)
                    .addGroup(addprofileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Supervisorbox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel69)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(aconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jLayeredPane2.add(addprofile, "card4");

        getContentPane().add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 940, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfileActionPerformed
        editprofile.setVisible(true);
        viewprofile.setVisible(false);
        addprofile.setVisible(false);
        blank.setVisible(false);
	try {
		Class.forName("com.ibm.db2.jcc.DB2Driver");
		con = DriverManager.getConnection(url);
		Statement sql1;
		ResultSet rs;
		String s1 = "Select "+Jets.UserType+"_NAME FROM "+Jets.UserType+" WHERE "+Jets.UserType+"_ID ='"+Jets.UserID+"'";
                String s2 = "Select "+Jets.UserType+"_GENDER FROM "+Jets.UserType+" WHERE "+Jets.UserType+"_ID ='"+Jets.UserID+"'";
		String s3 = "Select "+Jets.UserType+"_RACE FROM "+Jets.UserType+" WHERE "+Jets.UserType+"_ID ='"+Jets.UserID+"'";
                sql1 = con.createStatement();
                rs = sql1.executeQuery(s1);
		while (rs.next ()) {
			Name = rs.getString(1);
		}
                rs = sql1.executeQuery(s2);
		while (rs.next ()) {
			Gender = rs.getString(1);
		}
                rs = sql1.executeQuery(s3);
		while (rs.next ()) {
			Race = rs.getString(1);
		}       
		rs.close();
		sql1.close();
		con.close();
	} //end try	
        catch (ClassNotFoundException | SQLException e) {
        	System.out.println(e);
	}
        enamelabel.setText(Name);
        egenderlabel.setText(Gender);
        eracelabel.setText(Race);
    }//GEN-LAST:event_EditProfileActionPerformed

    private void AddProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProfileActionPerformed
        addprofile.setVisible(true);
        viewprofile.setVisible(false);
        editprofile.setVisible(false);
        blank.setVisible(false);
        if(Supervisorbox.getItemCount() == 0)
        {
            try {
		Class.forName("com.ibm.db2.jcc.DB2Driver");
		con = DriverManager.getConnection(url);
		Statement sql1;
		ResultSet rs;
		String s1 = "SELECT LECTURER_NAME FROM LECTURER";
                sql1 = con.createStatement();
                rs = sql1.executeQuery(s1);
		while (rs.next ()) {
                    Supervisorbox.addItem(rs.getString(1));      
		}
                rs.close();
		sql1.close();
		con.close();
            } //end try	
            catch (ClassNotFoundException | SQLException e) {
                        System.out.println(e);
            }
        }
        
    }//GEN-LAST:event_AddProfileActionPerformed

    private void ViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProfileActionPerformed
        viewprofile.setVisible(true);
        editprofile.setVisible(false);
        addprofile.setVisible(false);
        blank.setVisible(false);
        //System.out.println("User ID:" + Jets.UserID);
	try {
		Class.forName("com.ibm.db2.jcc.DB2Driver");
		con = DriverManager.getConnection(url);
		Statement sql1;
		ResultSet rs;
		String s1 = "Select "+Jets.UserType+"_NAME FROM "+Jets.UserType+" WHERE "+Jets.UserType+"_ID ='"+Jets.UserID+"'";
                String s2 = "Select "+Jets.UserType+"_GENDER FROM "+Jets.UserType+" WHERE "+Jets.UserType+"_ID ='"+Jets.UserID+"'";
		String s3 = "Select "+Jets.UserType+"_RACE FROM "+Jets.UserType+" WHERE "+Jets.UserType+"_ID ='"+Jets.UserID+"'";
                String s4 = "Select "+Jets.UserType+"_ADDRESS FROM "+Jets.UserType+" WHERE "+Jets.UserType+"_ID ='"+Jets.UserID+"'";
                String s5 = "Select "+Jets.UserType+"_CONTACT FROM "+Jets.UserType+" WHERE "+Jets.UserType+"_ID ='"+Jets.UserID+"'";
                String s6 = "Select "+Jets.UserType+"_EMAIL FROM "+Jets.UserType+" WHERE "+Jets.UserType+"_ID ='"+Jets.UserID+"'";
                sql1 = con.createStatement();
                rs = sql1.executeQuery(s1);
		while (rs.next ()) {
			Name = rs.getString(1);
		}
                rs = sql1.executeQuery(s2);
		while (rs.next ()) {
			Gender = rs.getString(1);
		}
                rs = sql1.executeQuery(s3);
		while (rs.next ()) {
			Race = rs.getString(1);
		}       
                rs = sql1.executeQuery(s4);
		while (rs.next ()) {
            		Address = rs.getString(1);
		}
                rs = sql1.executeQuery(s5);
		while (rs.next ()) {
			Contact = rs.getString(1);
                }
                rs = sql1.executeQuery(s6);
		while (rs.next ()) {
			Email = rs.getString(1);
		}
		rs.close();
		sql1.close();
		con.close();
	} //end try	
        catch (ClassNotFoundException | SQLException e) {
        	System.out.println(e);
	}
        namelabel.setText(Name);
        genderlabel.setText(Gender);
        racelabel.setText(Race);
        addresslabel.setText(Address);
        contactlabel.setText(Contact);
        emaillabel.setText(Email);
       
       
       
    }//GEN-LAST:event_ViewProfileActionPerformed

    private void econfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_econfirmActionPerformed
        String Add = addressfield.getText();
        String Con = contactfield.getText();
        String Mail = emailfield.getText();
        int Addlength = Add.length();
        int Conlength = Con.length();
        int Maillength = Mail.length();
        if (Add.equals("Not more than 100 characters") && Con.equals("Example: 012-3456789") && Mail.equals("Example: mail@mail.com"))
        {
            JOptionPane.showMessageDialog(null,"At least one field must be filled");
        }
        else if(Addlength>100 && !Add.equals("Not more than 100 characters") || Conlength>12 && !Con.equals("Example: 012-3456789") || Maillength>50 && !Mail.equals("Example: mail@mail.com"))
        {
            JOptionPane.showMessageDialog(null,"Exceed maximum character input");
            
        }
        else if(!Con.contains("-"))
        {
            JOptionPane.showMessageDialog(null,"Contact must have '-' in between ");
        }
        else
        {
            if (!Mail.equals("Example: mail@mail.com"))
            {
                try {
                       con = DriverManager.getConnection(url);
                       PreparedStatement pstmt;
                       int numUpd;          
                       pstmt = con.prepareStatement("UPDATE "+Jets.UserType+" SET "+Jets.UserType+"_EMAIL= '"+Mail+"' WHERE "+Jets.UserType+"_ID= '"+Jets.UserID+"'");
                       pstmt.execute();
                       pstmt.close();
                       con.close();
                }       
                catch (SQLException e) {
                    System.out.println(e);
                }
            }
            if (!Add.equals("Not more than 100 characters"))
            {
                try {
                    con = DriverManager.getConnection(url);
                    PreparedStatement pstmt;
                    int numUpd;      
                    pstmt = con.prepareStatement("UPDATE "+Jets.UserType+" SET "+Jets.UserType+"_ADDRESS= '"+Add+"' WHERE "+Jets.UserType+"_ID= '"+Jets.UserID+"'");
                    pstmt.execute();
                    pstmt.close();
                    con.close();
                }
                catch (SQLException e) {
                    System.out.println(e);
                }
            }
            if (!Con.equals("Example: 012-3456789"))
            {
                try {
                       con = DriverManager.getConnection(url);
                       PreparedStatement pstmt;
                       int numUpd;          
                       pstmt = con.prepareStatement("UPDATE "+Jets.UserType+" SET "+Jets.UserType+"_CONTACT= '"+Con+"' WHERE "+Jets.UserType+"_ID= '"+Jets.UserID+"'");
                       pstmt.execute();
                       pstmt.close();
                       con.close();
                }       
                catch (SQLException e) {
                    System.out.println(e);
                }
                
            }
            JOptionPane.showMessageDialog(null,"Updated succesfully");
                 
        } //end try
            
            
            addressfield.setText("Not more than 100 characters");
            addressfield.setForeground(new java.awt.Color(102,102,102));
            contactfield.setText("Example: 012-3456789");
            contactfield.setForeground(new java.awt.Color(102,102,102));
            emailfield.setText("Example: mail@mail.com");
            emailfield.setForeground(new java.awt.Color(102,102,102));
        
    }//GEN-LAST:event_econfirmActionPerformed

    private void aconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aconfirmActionPerformed
        String Type = String.valueOf(Typebox.getSelectedItem());
        String Course = String.valueOf(Coursebox.getSelectedItem());
        Name = aname.getText();
        Gender = String.valueOf(Genderbox.getSelectedItem());
        Race = String.valueOf(Racebox.getSelectedItem());
        Address = aaddressfield.getText();
        Contact = acontactfield.getText();
        Email = aemailfield.getText();
        String SupervisorID = String.valueOf(Supervisorbox.getSelectedItem());
        try {
		Class.forName("com.ibm.db2.jcc.DB2Driver");
		con = DriverManager.getConnection(url);
		Statement sql1;
		ResultSet rs;
		String s1 = "SELECT LECTURER_ID FROM LECTURER WHERE LECTURER_NAME = '"+SupervisorID+"'";
                sql1 = con.createStatement();
                rs = sql1.executeQuery(s1);
		while (rs.next ()) {
                    SupervisorID = rs.getString(1);      
		}
                rs.close();
		sql1.close();
		con.close();
            } //end try	
            catch (ClassNotFoundException | SQLException e) {
                        System.out.println(e);
            }
        
        if(Gender.equals("MALE"))
        {
            Gender = "M";
        }
        if(Gender.equals("FEMALE"))
        {
            Gender = "F";
        }
        if (Name.equals("Not more than 30 characters") || Address.equals("Not more than 100 characters") || Contact.equals("Example: 012-3456789") || Email.equals("Example: mail@mail.com"))
        {
            JOptionPane.showMessageDialog(null,"All field must be filled");
        }
        else if(Name.length()>30 && !Name.equals("Not more than 30 characters") || Address.length()>100 && !Address.equals("Not more than 100 characters") || Contact.length()>12 && !Contact.equals("Example: 012-3456789") || Email.length()>50 && !Email.equals("Example: mail@mail.com"))
        {
            JOptionPane.showMessageDialog(null,"Exceed maximum character input");
        }
        else if(!Contact.contains("-"))
        {
            JOptionPane.showMessageDialog(null,"Contact must have '-' in between ");
        }
        else if(!Type.equals("LECTURER")&&Supervisorbox.getItemCount()==0){
            JOptionPane.showMessageDialog(null, "Create at least 1 lecturer account first");
        }
        else
        {
            if(Type.equals("ADMIN"))
            {
                noAdmin = noAdmin + 1;
                String AdminID = null;
                if(noAdmin < 10)
                {
                    AdminID = "0" + String.valueOf(noAdmin);
                }
                if(noAdmin >= 10)
                {
                    AdminID = String.valueOf(noAdmin);
                }
                try {
                con = DriverManager.getConnection(url);
                PreparedStatement pstmt;
                pstmt = con.prepareStatement("INSERT INTO ADMIN VALUES('ADM-"+AdminID+"', '987654', '"+Name+"', '"+Gender+"', '"+Race+"', '"+Address+"', '"+Contact+"', '"+Email+"')");
                pstmt.execute();
                pstmt.close();
                con.close();
                } //end try
                catch (SQLException e) {
                    System.out.println(e);
                }   
                
                try {
                    con = DriverManager.getConnection(url);
                    PreparedStatement pstmt2;
                    pstmt2 = con.prepareStatement("UPDATE COUNTER SET RECORD = "+noAdmin+" WHERE COUNTER_ID = 'ADMIN'");
                    pstmt2.execute();
                    pstmt2.close();
                    con.close();
                    } //end try
                catch (SQLException e) {
                    System.out.println(e);
                }
                JOptionPane.showMessageDialog(null,"Profile successfully added");
            }
            if(Type.equals("LECTURER"))
            {
                noLecturer = noLecturer + 1;
                String LecturerID = null;
                if(noLecturer < 10)
                {
                    LecturerID = "000" +String.valueOf(noLecturer);
                }
                if(noLecturer >= 10)
                {
                    LecturerID = "00" +String.valueOf(noLecturer);
                }
                if(noLecturer >= 100)
                {
                    LecturerID = "0" +String.valueOf(noLecturer);
                }
                if(noLecturer >= 1000)
                {
                    LecturerID = String.valueOf(noLecturer);
                }
                
                //(LecturerID);
                try{
                    con = DriverManager.getConnection(url);
                    PreparedStatement pstmt;
                    pstmt = con.prepareStatement("INSERT INTO LECTURER VALUES('LEC-"+LecturerID+"', '123456', '"+Name+"', '"+Gender+"', '"+Race+"', '"+Address+"', '"+Contact+"', '"+Email+"')");
                    pstmt.execute();
                    pstmt.close();
                    con.close();
                }
                catch (SQLException e) {
                    System.out.println(e);
                }

                try {
                    con = DriverManager.getConnection(url);
                    PreparedStatement pstmt2;
                    pstmt2 = con.prepareStatement("UPDATE COUNTER SET RECORD = "+noLecturer+" WHERE COUNTER_ID = 'LECTURER'");
                    pstmt2.execute();
                    pstmt2.close();
                    con.close();
                    } //end try
                catch (SQLException e) {
                    System.out.println(e);
                }
                JOptionPane.showMessageDialog(null,"Profile successfully added");        
            }
      
            if(Type.equals("STUDENT"))
            {
                Calendar now = Calendar.getInstance();
		String year = String.valueOf(now.get(Calendar.YEAR));
                noStudent = noStudent + 1;
                String StudentID = null;
                if(noStudent <10)
                {
                    StudentID = "00000" + String.valueOf(noStudent);
                }
                if(noStudent >= 10)
                {
                    StudentID = "0000" + String.valueOf(noStudent);
                }
                if(noStudent >= 100)
                {
                    StudentID = "000" + String.valueOf(noStudent);
                }
                if(noStudent >= 1000)
                {
                    StudentID = "00" + String.valueOf(noStudent);
                }
                if(noStudent >= 10000)
                {
                    StudentID = "0" + String.valueOf(noStudent);
                }
                if(noStudent >= 100000)
                {
                    StudentID = String.valueOf(noStudent);
                }
                
                //System.out.println(StudentID);
                try{
                    con = DriverManager.getConnection(url);
                    PreparedStatement pstmt;
                    pstmt = con.prepareStatement("INSERT INTO STUDENT VALUES('"+year+StudentID+"', '123456', '"+Name+"', '"+Gender+"', '"+Race+"', '"+Address+"', '"+Contact+"', '"+Email+"', '7057788999','"+Course+"', '"+SupervisorID+"' )");
                    pstmt.execute();
                    pstmt.close();
                    con.close();
                }
                catch (SQLException e) {
                    System.out.println(e);
                }
                try {
                    con = DriverManager.getConnection(url);
                    PreparedStatement pstmt2;
                    pstmt2 = con.prepareStatement("UPDATE COUNTER SET RECORD = "+noStudent+" WHERE COUNTER_ID = 'STUDENT'");
                    pstmt2.execute();
                    pstmt2.close();
                    con.close();
                    } //end try
                catch (SQLException e) {
                    System.out.println(e);
                }
                JOptionPane.showMessageDialog(null,"Profile successfully added");
                
                Supervisorbox.removeAllItems();
                if(Supervisorbox.getItemCount() == 0)
                {
                    try {
                        Class.forName("com.ibm.db2.jcc.DB2Driver");
                        con = DriverManager.getConnection(url);
                        Statement sql1;
                        ResultSet rs;
                        String s1 = "SELECT LECTURER_NAME FROM LECTURER";
                        sql1 = con.createStatement();
                        rs = sql1.executeQuery(s1);
                        while (rs.next ()) {
                            Supervisorbox.addItem(rs.getString(1));      
                        }
                        rs.close();
                        sql1.close();
                        con.close();
                    } //end try	
                    catch (ClassNotFoundException | SQLException e) {
                                System.out.println(e);
                    }
                }
            }
            aname.setText("Not more than 30 characters");
            aname.setForeground(new java.awt.Color(102,102,102));
            aaddressfield.setText("Not more than 100 characters");
            aaddressfield.setForeground(new java.awt.Color(102,102,102));
            acontactfield.setText("Example: 012-3456789");
            acontactfield.setForeground(new java.awt.Color(102,102,102));
            aemailfield.setText("Example: mail@mail.com");
            aemailfield.setForeground(new java.awt.Color(102,102,102));
        }
        
        
    }//GEN-LAST:event_aconfirmActionPerformed

    private void CourseboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CourseboxActionPerformed

    private void jLabel17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MousePressed
        // TODO add your handling code here:
        if (Jets.UserType.equals("STUDENT"))
            new StudentMainMenu().setVisible(true);
        if (Jets.UserType.equals("ADMIN"))
            new AdminMainMenu().setVisible(true);
        if (Jets.UserType.equals("LECTURER"))
            new LecturerMainMenu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel17MousePressed

    private void addressfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressfieldFocusGained
        if(addressfield.getText().equals("Not more than 100 characters"))
        {
            addressfield.setForeground(new java.awt.Color(0,0,0));
            addressfield.setText("");
        }
    }//GEN-LAST:event_addressfieldFocusGained

    private void addressfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressfieldFocusLost
        if(addressfield.getText().equals(""))
        {
            addressfield.setForeground(new java.awt.Color(102,102,102));
            addressfield.setText("Not more than 100 characters");
        }
    }//GEN-LAST:event_addressfieldFocusLost

    private void contactfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactfieldFocusGained
        if(contactfield.getText().equals("Example: 012-3456789"))
        {
            contactfield.setForeground(new java.awt.Color(0,0,0));
            contactfield.setText("");
        }
    }//GEN-LAST:event_contactfieldFocusGained

    private void contactfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactfieldFocusLost
        if(contactfield.getText().equals(""))
        {
            contactfield.setForeground(new java.awt.Color(102,102,102));
            contactfield.setText("Example: 012-3456789");
        }
    }//GEN-LAST:event_contactfieldFocusLost

    private void emailfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailfieldFocusGained
        if(emailfield.getText().equals("Example: mail@mail.com"))
        {
            emailfield.setForeground(new java.awt.Color(0,0,0));
            emailfield.setText("");
        }
    }//GEN-LAST:event_emailfieldFocusGained

    private void emailfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailfieldFocusLost
        if(emailfield.getText().equals(""))
        {
            emailfield.setForeground(new java.awt.Color(102,102,102));
            emailfield.setText("Example: mail@mail.com");
        }
    }//GEN-LAST:event_emailfieldFocusLost

    private void anameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_anameFocusGained
        if(aname.getText().equals("Not more than 30 characters"))
        {
            aname.setForeground(new java.awt.Color(0,0,0));
            aname.setText("");
        }
    }//GEN-LAST:event_anameFocusGained

    private void anameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_anameFocusLost
        if(aname.getText().equals(""))
        {
            aname.setForeground(new java.awt.Color(102,102,102));
            aname.setText("Not more than 30 characters");
        }
    }//GEN-LAST:event_anameFocusLost

    private void aaddressfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aaddressfieldFocusGained
         if(aaddressfield.getText().equals("Not more than 100 characters"))
        {
            aaddressfield.setForeground(new java.awt.Color(0,0,0));
            aaddressfield.setText("");
        }
    }//GEN-LAST:event_aaddressfieldFocusGained

    private void aaddressfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aaddressfieldFocusLost
        if(aaddressfield.getText().equals(""))
        {
            aaddressfield.setForeground(new java.awt.Color(102,102,102));
            aaddressfield.setText("Not more than 100 characters");
        }
    }//GEN-LAST:event_aaddressfieldFocusLost

    private void acontactfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acontactfieldFocusGained
        if(acontactfield.getText().equals("Example: 012-3456789"))
        {
            acontactfield.setForeground(new java.awt.Color(0,0,0));
            acontactfield.setText("");
        }
    }//GEN-LAST:event_acontactfieldFocusGained

    private void acontactfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acontactfieldFocusLost
        if(acontactfield.getText().equals(""))
        {
            acontactfield.setForeground(new java.awt.Color(102,102,102));
            acontactfield.setText("Example: 012-3456789");
        }
    }//GEN-LAST:event_acontactfieldFocusLost

    private void aemailfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aemailfieldFocusGained
        if(aemailfield.getText().equals("Example: mail@mail.com"))
        {
            aemailfield.setForeground(new java.awt.Color(0,0,0));
            aemailfield.setText("");
        }
    }//GEN-LAST:event_aemailfieldFocusGained

    private void aemailfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aemailfieldFocusLost
        if(aemailfield.getText().equals(""))
        {
            aemailfield.setForeground(new java.awt.Color(102,102,102));
            aemailfield.setText("Example: mail@mail.com");
        }
    }//GEN-LAST:event_aemailfieldFocusLost

    private void SupervisorboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupervisorboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupervisorboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ProfileManagement().setVisible(true);
        });
    }
    
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProfile;
    private javax.swing.JComboBox<String> Coursebox;
    private javax.swing.JButton EditProfile;
    private javax.swing.JComboBox<String> Genderbox;
    private javax.swing.JComboBox<String> Racebox;
    private javax.swing.JComboBox<String> Supervisorbox;
    private javax.swing.JComboBox<String> Typebox;
    private javax.swing.JButton ViewProfile;
    private javax.swing.JTextField aaddressfield;
    private javax.swing.JButton aconfirm;
    private javax.swing.JTextField acontactfield;
    private javax.swing.JPanel addprofile;
    private javax.swing.JTextField addressfield;
    private javax.swing.JTextArea addresslabel;
    private javax.swing.JTextField aemailfield;
    private javax.swing.JTextField aname;
    private javax.swing.JPanel blank;
    private javax.swing.JTextField contactfield;
    private javax.swing.JLabel contactlabel;
    private javax.swing.JButton econfirm;
    private javax.swing.JPanel editprofile;
    private javax.swing.JLabel egenderlabel;
    private javax.swing.JTextField emailfield;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JLabel enamelabel;
    private javax.swing.JLabel eracelabel;
    private javax.swing.JLabel genderlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel namelabel;
    private javax.swing.JLabel racelabel;
    private javax.swing.JPanel viewprofile;
    // End of variables declaration//GEN-END:variables
}
