/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jets;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alfre
 */
public class StudentExamination extends javax.swing.JFrame {

    LinkedList<ExamSlip> slipList = new LinkedList<>();
    LinkedList<ExamResult> resultList = new LinkedList<>();
    DefaultTableModel slipModel = new DefaultTableModel(){
        public boolean isCellEditable(int row, int column)
        {
            return false;
        }
    };
    DefaultTableModel resultModel = new DefaultTableModel(){
        public boolean isCellEditable(int row, int column)
        {
            return false;
        }
    };
    String url = "jdbc:db2:PMS";
    /**
     * Creates new form StudentExamination
     */
    public StudentExamination() {
        initComponents();
        readExamSlip();
        readExamResult();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContentPanel = new javax.swing.JPanel();
        ContentVES = new javax.swing.JPanel();
        CVESLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ExamSlipTable = new javax.swing.JTable();
        SubjectName = new javax.swing.JLabel();
        SubjectTimeText = new javax.swing.JTextField();
        SubjectDate = new javax.swing.JLabel();
        SubjectTime = new javax.swing.JLabel();
        SubjectDateText = new javax.swing.JTextField();
        SubjectSeat = new javax.swing.JLabel();
        SubjectSeatText = new javax.swing.JTextField();
        SubjectNameText = new javax.swing.JTextField();
        ContentVER = new javax.swing.JPanel();
        CVERLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ExamResultTable = new javax.swing.JTable();
        ERSubCH = new javax.swing.JLabel();
        ERSubGrade = new javax.swing.JLabel();
        ERSubName = new javax.swing.JLabel();
        ERSubNameText = new javax.swing.JTextField();
        ERSubGradeText = new javax.swing.JTextField();
        ERSubCHText = new javax.swing.JTextField();
        ERSubGPA = new javax.swing.JLabel();
        ERSubGPAText = new javax.swing.JTextField();
        ERSubCGPA = new javax.swing.JLabel();
        ERSubCGPAText = new javax.swing.JTextField();
        ContentMainPanel = new javax.swing.JPanel();
        ELabel2 = new javax.swing.JLabel();
        VERLabel2 = new javax.swing.JLabel();
        VESLabel2 = new javax.swing.JLabel();
        MenuPanel = new javax.swing.JPanel();
        HomeLabel = new javax.swing.JLabel();
        HomeIconLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        VERPanel = new javax.swing.JPanel();
        VERLabel = new javax.swing.JLabel();
        ViewNotificationIconLabel = new javax.swing.JLabel();
        VESPanel = new javax.swing.JPanel();
        VESLabel = new javax.swing.JLabel();
        GenerateNotificationIconLabel = new javax.swing.JLabel();
        EPanel = new javax.swing.JPanel();
        ELabel = new javax.swing.JLabel();
        NotificationIconLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student- Examination");
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ContentPanel.setLayout(new java.awt.CardLayout());

        ContentVES.setBackground(new java.awt.Color(255, 255, 255));
        ContentVES.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CVESLabel.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        CVESLabel.setForeground(new java.awt.Color(0, 0, 0));
        CVESLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CVESLabel.setText("View Exam Slip");
        ContentVES.add(CVESLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 880, 40));

        ExamSlipTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ExamSlipTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ExamSlipTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExamSlipTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ExamSlipTable);

        ContentVES.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 880, 270));

        SubjectName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SubjectName.setForeground(new java.awt.Color(0, 0, 0));
        SubjectName.setText("Subject Name                                :");
        ContentVES.add(SubjectName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 290, 40));

        SubjectTimeText.setEditable(false);
        SubjectTimeText.setForeground(new java.awt.Color(0, 0, 0));
        ContentVES.add(SubjectTimeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, 500, 40));

        SubjectDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SubjectDate.setForeground(new java.awt.Color(0, 0, 0));
        SubjectDate.setText("Subject Date                                  :");
        ContentVES.add(SubjectDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 290, 40));

        SubjectTime.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SubjectTime.setForeground(new java.awt.Color(0, 0, 0));
        SubjectTime.setText("Subject Time                                 :");
        ContentVES.add(SubjectTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 290, 40));

        SubjectDateText.setEditable(false);
        SubjectDateText.setForeground(new java.awt.Color(0, 0, 0));
        ContentVES.add(SubjectDateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 500, 40));

        SubjectSeat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SubjectSeat.setForeground(new java.awt.Color(0, 0, 0));
        SubjectSeat.setText("Subject Seat                                 :");
        ContentVES.add(SubjectSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 290, 40));

        SubjectSeatText.setEditable(false);
        SubjectSeatText.setForeground(new java.awt.Color(0, 0, 0));
        ContentVES.add(SubjectSeatText, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 640, 500, 40));

        SubjectNameText.setEditable(false);
        SubjectNameText.setForeground(new java.awt.Color(0, 0, 0));
        ContentVES.add(SubjectNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 500, 40));

        ContentPanel.add(ContentVES, "card3");

        ContentVER.setBackground(new java.awt.Color(255, 255, 255));
        ContentVER.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CVERLabel.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        CVERLabel.setForeground(new java.awt.Color(0, 0, 0));
        CVERLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CVERLabel.setText("View Exam Result");
        ContentVER.add(CVERLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 880, 40));

        ExamResultTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ExamResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ExamResultTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExamResultTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ExamResultTable);

        ContentVER.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 880, 270));

        ERSubCH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ERSubCH.setForeground(new java.awt.Color(0, 0, 0));
        ERSubCH.setText("Subject Credit Hour                      :");
        ContentVER.add(ERSubCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 290, 40));

        ERSubGrade.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ERSubGrade.setForeground(new java.awt.Color(0, 0, 0));
        ERSubGrade.setText("Subject Grade                               :");
        ContentVER.add(ERSubGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 290, 40));

        ERSubName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ERSubName.setForeground(new java.awt.Color(0, 0, 0));
        ERSubName.setText("Subject Name                                :");
        ContentVER.add(ERSubName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 290, 40));

        ERSubNameText.setEditable(false);
        ContentVER.add(ERSubNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 500, 40));

        ERSubGradeText.setEditable(false);
        ContentVER.add(ERSubGradeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, 500, 40));

        ERSubCHText.setEditable(false);
        ContentVER.add(ERSubCHText, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 500, 40));

        ERSubGPA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ERSubGPA.setForeground(new java.awt.Color(0, 0, 0));
        ERSubGPA.setText("Subject GPA                                  :");
        ContentVER.add(ERSubGPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 290, 40));

        ERSubGPAText.setEditable(false);
        ContentVER.add(ERSubGPAText, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 600, 500, 40));

        ERSubCGPA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ERSubCGPA.setForeground(new java.awt.Color(0, 0, 0));
        ERSubCGPA.setText("Current CGPA                               :");
        ContentVER.add(ERSubCGPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 290, 40));

        ERSubCGPAText.setEditable(false);
        ContentVER.add(ERSubCGPAText, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 670, 500, 40));

        ContentPanel.add(ContentVER, "card4");

        ContentMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        ContentMainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ELabel2.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        ELabel2.setForeground(new java.awt.Color(0, 0, 0));
        ELabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ELabel2.setText("Examination");
        ContentMainPanel.add(ELabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 880, 40));

        VERLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        VERLabel2.setForeground(new java.awt.Color(0, 0, 0));
        VERLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VERLabel2.setText("View Exam Result");
        VERLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        VERLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VERLabel2MousePressed(evt);
            }
        });
        ContentMainPanel.add(VERLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 250, 60));

        VESLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        VESLabel2.setForeground(new java.awt.Color(0, 0, 0));
        VESLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VESLabel2.setText("View Exam Slip");
        VESLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        VESLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VESLabel2MousePressed(evt);
            }
        });
        ContentMainPanel.add(VESLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 250, 60));

        ContentPanel.add(ContentMainPanel, "card4");

        getContentPane().add(ContentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 940, 720));

        MenuPanel.setBackground(new java.awt.Color(50, 100, 255));
        MenuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        HomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HomeLabel.setText("Home");
        MenuPanel.add(HomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 270, 40));

        HomeIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomeIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Back_Arrow_32px_3.png"))); // NOI18N
        HomeIconLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HomeIconLabelMousePressed(evt);
            }
        });
        MenuPanel.add(HomeIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 40));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setPreferredSize(new java.awt.Dimension(1, 1));
        MenuPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 340, 10));

        VERPanel.setBackground(new java.awt.Color(60, 100, 255));
        VERPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VERLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        VERLabel.setForeground(new java.awt.Color(255, 255, 255));
        VERLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        VERLabel.setText("View Exam Result");
        VERLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VERLabelMousePressed(evt);
            }
        });
        VERPanel.add(VERLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 270, 50));

        ViewNotificationIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ViewNotificationIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_View_24px.png"))); // NOI18N
        VERPanel.add(ViewNotificationIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 50));

        MenuPanel.add(VERPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 340, 50));

        VESPanel.setBackground(new java.awt.Color(60, 100, 255));
        VESPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VESLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        VESLabel.setForeground(new java.awt.Color(255, 255, 255));
        VESLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        VESLabel.setText("View Exam Slip");
        VESLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VESLabelMousePressed(evt);
            }
        });
        VESPanel.add(VESLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 270, 50));

        GenerateNotificationIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GenerateNotificationIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_View_24px.png"))); // NOI18N
        VESPanel.add(GenerateNotificationIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 50));

        MenuPanel.add(VESPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 340, 50));

        EPanel.setBackground(new java.awt.Color(60, 100, 255));
        EPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ELabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        ELabel.setForeground(new java.awt.Color(255, 255, 255));
        ELabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ELabel.setText("Examination");
        ELabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ELabelMousePressed(evt);
            }
        });
        EPanel.add(ELabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 270, 50));

        NotificationIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NotificationIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Exam_30px.png"))); // NOI18N
        EPanel.add(NotificationIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 50));

        MenuPanel.add(EPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 340, 50));

        getContentPane().add(MenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VERLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VERLabel2MousePressed
        // TODO add your handling code here:
        ContentMainPanel.setVisible(false);
        ContentVES.setVisible(false);
        ContentVER.setVisible(true);
        //retrieveNotification();
    }//GEN-LAST:event_VERLabel2MousePressed

    private void VESLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VESLabel2MousePressed
        // TODO add your handling code here:
        ContentVES.setVisible(true);
        ContentMainPanel.setVisible(false);
        ContentVER.setVisible(false);
    }//GEN-LAST:event_VESLabel2MousePressed

    private void HomeIconLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeIconLabelMousePressed
        // TODO add your handling code here:
        if (Jets.UserType.equals("STUDENT"))
            new StudentMainMenu().setVisible(true);
        if (Jets.UserType.equals("ADMIN"))
            new AdminMainMenu().setVisible(true);
        if (Jets.UserType.equals("LECTURER"))
            new LecturerMainMenu().setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeIconLabelMousePressed

    private void VERLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VERLabelMousePressed
        // TODO add your handling code here:
        ContentMainPanel.setVisible(false);
        ContentVES.setVisible(false);
        ContentVER.setVisible(true);
        //retrieveNotification();
    }//GEN-LAST:event_VERLabelMousePressed

    private void VESLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VESLabelMousePressed
        // TODO add your handling code here:
        ContentVES.setVisible(true);
        ContentMainPanel.setVisible(false);
        ContentVER.setVisible(false);
    }//GEN-LAST:event_VESLabelMousePressed

    private void ELabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ELabelMousePressed
        // TODO add your handling code here:
        ContentMainPanel.setVisible(true);
        ContentVES.setVisible(false);
        ContentVER.setVisible(false);
    }//GEN-LAST:event_ELabelMousePressed

    private void ExamSlipTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExamSlipTableMouseClicked
        // TODO add your handling code here:
        int x = ExamSlipTable.getSelectedRow();
        SubjectNameText.setText(slipList.get(x).getID());
        SubjectDateText.setText(slipList.get(x).getDate());
        SubjectTimeText.setText(slipList.get(x).getTime());
        SubjectSeatText.setText(Integer.toString(slipList.get(x).getSeat()));
    }//GEN-LAST:event_ExamSlipTableMouseClicked

    private void ExamResultTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExamResultTableMouseClicked
        // TODO add your handling code here:
        int x = ExamResultTable.getSelectedRow();
        ERSubNameText.setText(resultList.get(x).getID());
        ERSubCHText.setText(Integer.toString(resultList.get(x).getTotalCreditHour()));
        ERSubGradeText.setText(resultList.get(x).getGrade());
        ERSubGPAText.setText(Double.toString(resultList.get(x).getGpa()));
    }//GEN-LAST:event_ExamResultTableMouseClicked

    public void readExamSlip(){
        slipList.clear();
        String subName;
        String subDate;
        String subTime;
        String subSeat;
        
        Connection con;
        
        try{
            Class.forName("com.ibm.db2.jcc.DB2Driver");
            con = DriverManager.getConnection(url);

            Statement sql1;
            ResultSet rs1;
            String s1 = "select timetable_id, subject_name, timetable_date, "
                    + "timetable_time, timetable_seat from timetable t, trimester s, "
                    + "subject x where t.trimester_id = s.trimester_id and "
                    + "s.subject_id = x.subject_id and student_id = '"
                    + Jets.UserID 
                    + "'";
            sql1= con.createStatement();
            rs1 = sql1.executeQuery(s1);
            while (rs1.next()){
                subName = rs1.getString("subject_name");
                subDate = rs1.getString("timetable_date");
                subTime = rs1.getString("timetable_time");
                subSeat = rs1.getString("timetable_seat");
                int x = Integer.parseInt(subSeat);
                slipList.add(new ExamSlip(subName, subDate, subTime, x));
            }
            rs1.close();
            sql1.close();

            con.close();
        }
        catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        } 
        if (slipList.size()>0){
            slipModel = (DefaultTableModel) ExamSlipTable.getModel();
            Object[][] notificationData = {
                {slipList.get(0).getID(), slipList.get(0).getDate(), slipList.get(0).getTime(), slipList.get(0).getSeat()}
            }; 
            String[] notificationColName = {
                "Subject Name", "Subject Date" , "Subject Time", "Subject Seat"
            };
            slipModel.setDataVector(notificationData, notificationColName);
            //i = x-1 -> get the second last element
            for (int i=1;i<slipList.size();i++){
                slipModel.addRow(new Object[]{slipList.get(i).getID(), slipList.get(i).getDate(), slipList.get(i).getTime(), slipList.get(i).getSeat()});
            }
            ExamSlipTable.setModel(slipModel);
        }
        else{
            Object[][] Subjectdata =
                {
                    {}
                };
            String[] SubjectcolName = {"Subject Name", "Subject Date" , "Subject Time", "Subject Seat"};
            slipModel.setDataVector(Subjectdata, SubjectcolName);
            slipModel.removeRow(0);
            ExamSlipTable.setModel(slipModel);
        }
        
        
    }
    
    public void readExamResult(){
        resultList.clear();
        String subName;
        String subCH;
        String subGrade;
        String subGPA;
        double gpa;
        int ch;
        double total=0;
        double chTotal=0;
        Connection con;
        
        try{
            Class.forName("com.ibm.db2.jcc.DB2Driver");
            con = DriverManager.getConnection(url);

            Statement sql1;
            ResultSet rs1;
            String s1 = "select subject_name, credit_hour, grade, "
                    + "gpa from subject s, trimester t, exam_result e "
                    + "where e.trimester_id = t.trimester_id and "
                    + "s.subject_id = t.subject_id and student_id = '"
                    + Jets.UserID 
                    + "'";
            sql1= con.createStatement();
            rs1 = sql1.executeQuery(s1);
            while (rs1.next()){
                subName = rs1.getString("subject_name");
                subCH = rs1.getString("credit_hour");
                subGrade = rs1.getString("grade");
                subGPA = rs1.getString("gpa");
                gpa = Double.parseDouble(subGPA);
                ch = Integer.parseInt(subCH);
                total += gpa*ch;
                chTotal+=ch;
                resultList.add(new ExamResult(subName, subGrade, gpa, ch));
            }
            rs1.close();
            sql1.close();
            
            con.close();
        }
        catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        } 
        double cgpa = total/chTotal;
        String result = String.format("%.2f", cgpa);
        ERSubCGPAText.setText(result);
        if (resultList.size()>0){
            resultModel = (DefaultTableModel) ExamResultTable.getModel();
            Object[][] notificationData = {
                {resultList.get(0).getID(), resultList.get(0).getTotalCreditHour(), resultList.get(0).getGrade(), resultList.get(0).getGpa()}
            }; 
            String[] notificationColName = {
                "Subject Name", "Subject Credit Hour" , "Subject Grade", "Subject GPA"
            };
            resultModel.setDataVector(notificationData, notificationColName);
            //i = x-1 -> get the second last element
            for (int i=1;i<resultList.size();i++){
                resultModel.addRow(new Object[]{resultList.get(i).getID(), resultList.get(i).getTotalCreditHour(), resultList.get(i).getGrade(), resultList.get(i).getGpa()});
            }
            ExamResultTable.setModel(resultModel);
        }
        else{
            Object[][] Subjectdata =
                {
                    {}
                };
            String[] SubjectcolName = {"Subject Name", "Subject Credit Hour" , "Subject Grade", "Subject GPA"};
            resultModel.setDataVector(Subjectdata, SubjectcolName);
            resultModel.removeRow(0);
            ExamResultTable.setModel(resultModel);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentExamination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentExamination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentExamination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentExamination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentExamination().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CVERLabel;
    private javax.swing.JLabel CVESLabel;
    private javax.swing.JPanel ContentMainPanel;
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JPanel ContentVER;
    private javax.swing.JPanel ContentVES;
    private javax.swing.JLabel ELabel;
    private javax.swing.JLabel ELabel2;
    private javax.swing.JPanel EPanel;
    private javax.swing.JLabel ERSubCGPA;
    private javax.swing.JTextField ERSubCGPAText;
    private javax.swing.JLabel ERSubCH;
    private javax.swing.JTextField ERSubCHText;
    private javax.swing.JLabel ERSubGPA;
    private javax.swing.JTextField ERSubGPAText;
    private javax.swing.JLabel ERSubGrade;
    private javax.swing.JTextField ERSubGradeText;
    private javax.swing.JLabel ERSubName;
    private javax.swing.JTextField ERSubNameText;
    private javax.swing.JTable ExamResultTable;
    private javax.swing.JTable ExamSlipTable;
    private javax.swing.JLabel GenerateNotificationIconLabel;
    private javax.swing.JLabel HomeIconLabel;
    private javax.swing.JLabel HomeLabel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JLabel NotificationIconLabel;
    private javax.swing.JLabel SubjectDate;
    private javax.swing.JTextField SubjectDateText;
    private javax.swing.JLabel SubjectName;
    private javax.swing.JTextField SubjectNameText;
    private javax.swing.JLabel SubjectSeat;
    private javax.swing.JTextField SubjectSeatText;
    private javax.swing.JLabel SubjectTime;
    private javax.swing.JTextField SubjectTimeText;
    private javax.swing.JLabel VERLabel;
    private javax.swing.JLabel VERLabel2;
    private javax.swing.JPanel VERPanel;
    private javax.swing.JLabel VESLabel;
    private javax.swing.JLabel VESLabel2;
    private javax.swing.JPanel VESPanel;
    private javax.swing.JLabel ViewNotificationIconLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
