/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jets;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author FOOCK
 */
public class UserLogin extends javax.swing.JFrame {
    /**
     * Creates new form UserLogin
     */  
    LinkedList<User> user = new LinkedList<>();
    String url = "jdbc:db2:PMS"; //database name
    Connection con;

    
    public UserLogin() {
        initComponents();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resetpass = new javax.swing.JDialog();
        ruserID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        resetconfirm = new javax.swing.JButton();
        remail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rnewPass = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();

        resetpass.setMinimumSize(new java.awt.Dimension(640, 480));
        resetpass.setSize(new java.awt.Dimension(640, 480));

        ruserID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ruserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruserIDActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("User ID:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("New Password:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel7.setText("RESET PASSWORD");

        resetconfirm.setText("Confirm");
        resetconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetconfirmActionPerformed(evt);
            }
        });

        remail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        remail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remailActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Email:");

        jLabel9.setText("Not more than 30 characters");

        javax.swing.GroupLayout resetpassLayout = new javax.swing.GroupLayout(resetpass.getContentPane());
        resetpass.getContentPane().setLayout(resetpassLayout);
        resetpassLayout.setHorizontalGroup(
            resetpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resetpassLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(resetpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resetconfirm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resetpassLayout.createSequentialGroup()
                        .addGroup(resetpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resetpassLayout.createSequentialGroup()
                                .addGroup(resetpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8))
                                .addGap(63, 63, 63))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resetpassLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(resetpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ruserID)
                            .addComponent(remail, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                            .addComponent(jLabel9)
                            .addComponent(rnewPass))))
                .addGap(24, 24, 24))
            .addGroup(resetpassLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel7)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        resetpassLayout.setVerticalGroup(
            resetpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resetpassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(resetpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruserID, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(resetpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rnewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(4, 4, 4)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(resetpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remail, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(24, 24, 24)
                .addComponent(resetconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User- Login");
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel2.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel2.setPreferredSize(new java.awt.Dimension(1280, 720));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("USER ID:");
        jLabel3.setAlignmentY(0.0F);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("PASSWORD:");

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reset Password");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mmu_full_logo-1.png"))); // NOI18N
        jLabel5.setAlignmentY(0.0F);

        jLabel2.setText(" © Copyrighted by JETS 2017");

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("POSTGRADUATE MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(415, 415, 415)
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(275, 275, 275)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(489, 489, 489)
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 284, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addGap(74, 74, 74)
                .addComponent(jLabel10)
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        resetpass.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            if(user.size() <= 0)
            {
                getUser(user);
            }
            Boolean checkID = false;
            Boolean checkPass = false;
            String ID = jTextField1.getText();
            String Type = null; 
            String name = null;
            for(int i=0; i<user.size();i++)
            {
                if((jTextField1.getText()).equals(user.get(i).getID()))
                {
                    checkID = true;
                    char[] temp;
                    temp = jPasswordField1.getPassword();
                    String pass = String.valueOf(temp);
                    if(pass.equals(user.get(i).getPassword()))
                    {
                        checkPass = true;
                        Type = user.get(i).gettype();
                        name = user.get(i).getName();
                        break;
                    }
                    else
                    {
                        jPasswordField1.setText("");
                        break;
                    }
                }
                /*
                else
                {
                    jTextField1.setText("");
                    jPasswordField1.setText("");
                }*/
            }
            if(checkID && checkPass)
            {
                JOptionPane.showMessageDialog(null,"Login Successful");
                Jets.UserID = ID;
                Jets.UserType = Type;
                Jets.UserName = name;
                System.out.println("User ID:" + Jets.UserID);
                System.out.println("User Type:" + Jets.UserType);
                if (Jets.UserType.equals("STUDENT"))
                    new StudentMainMenu().setVisible(true);
                if (Jets.UserType.equals("ADMIN"))
                    new AdminMainMenu().setVisible(true);
                if (Jets.UserType.equals("LECTURER"))
                    new LecturerMainMenu().setVisible(true);
                user.clear();
                dispose();
            }
            if(!checkID || !checkPass)
            {
                JOptionPane.showMessageDialog(null,"Your ID or password is incorrect");
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ruserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruserIDActionPerformed

    private void resetconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetconfirmActionPerformed
        if(user.size() <= 0)
        {
            getUser(user);
        }
        String ID = ruserID.getText();
        String newPass = null;
        String type = null;
        String Email = null;
        Boolean check = false;
        Boolean emailcheck = false;
        for(int i=0; i<user.size();i++)
        {
            if(ID.equals(user.get(i).getID()))
            {
                type = user.get(i).gettype();
                newPass = String.valueOf(rnewPass.getPassword());
                int newPasslength = rnewPass.getPassword().length;
                if(newPasslength <= 30)
                {
                    check = true;
                }
                break;
            }        
        }
        
        if(check)
        {
            try {
		Class.forName("com.ibm.db2.jcc.DB2Driver");
		con = DriverManager.getConnection(url);
		Statement sql1;
		ResultSet rs;
		String s1 = "SELECT STUDENT_EMAIL FROM STUDENT WHERE STUDENT_ID = '"+ID+"'";
                String s2 = "SELECT LECTURER_EMAIL FROM LECTURER WHERE LECTURER_ID = '"+ID+"'";
                String s3 = "SELECT ADMIN_EMAIL FROM ADMIN WHERE ADMIN_ID = '"+ID+"'";
		sql1 = con.createStatement();
		rs = sql1.executeQuery(s1);
		while (rs.next ()) {
                    if(rs.getString(1)!= null)
                    {
                        Email = rs.getString(1);
                    }
		}
                rs = sql1.executeQuery(s2);
		while (rs.next ()) {
                    if(rs.getString(1)!= null)
                    {
                        Email = rs.getString(1);
                    }
		}
                rs = sql1.executeQuery(s3);
		while (rs.next ()) {
                    if(rs.getString(1)!= null)
                    {
                        Email = rs.getString(1);
                    }
		}
            }
            catch (ClassNotFoundException | SQLException e) {
		System.out.println(e);
            }
            
            if(remail.getText().equals(Email))
            {
                emailcheck = true;
            }
            
            if(emailcheck)
            {
                try {
                    con = DriverManager.getConnection(url);
                    PreparedStatement pstmt;
                    int numUpd;
                    pstmt = con.prepareStatement("UPDATE "+type+" SET "+type+"_PASSWORD= '"+newPass+"' WHERE "+type+"_ID= '"+ID+"'");
                    pstmt.execute();
                    pstmt.close();
                    con.close();
                } //end try
                    catch (SQLException e) {
                    System.out.println(e);
                }
                JOptionPane.showMessageDialog(null,"Reset password succesful");
                resetpass.setVisible(false);
                ruserID.setText("");
                rnewPass.setText("");
                remail.setText("");
                user.clear();
                if(user.size() <= 0)
                {
                    getUser(user);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Invalid ID or Email");
                ruserID.setText("");
                rnewPass.setText("");
                remail.setText("");
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Invalid ID or Email, exceed password length");
            ruserID.setText("");
            rnewPass.setText("");
            remail.setText("");
        }
        
    }//GEN-LAST:event_resetconfirmActionPerformed

    private void remailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
           new UserLogin().setVisible(true);
        });
    }
    
    public void getUser(LinkedList<User> allUser)
    {
        String ID;
        String Pass;
        String name;
	try {
                Class.forName("com.ibm.db2.jcc.DB2Driver");
		con = DriverManager.getConnection(url);
		Statement sql1;
		ResultSet rs;
		String s1 = "SELECT STUDENT_ID,STUDENT_PASSWORD,STUDENT_NAME FROM STUDENT";
                String s2 = "SELECT LECTURER_ID,LECTURER_PASSWORD,LECTURER_NAME FROM LECTURER";
                String s3 = "SELECT ADMIN_ID,ADMIN_PASSWORD,ADMIN_NAME FROM ADMIN";
		sql1 = con.createStatement();
		rs = sql1.executeQuery(s1);
		while (rs.next ()) {
                    ID = rs.getString(1);
                    Pass = rs.getString(2);
                    name = rs.getString(3);
                    user.add(new User(ID,Pass,"STUDENT",name));
		}
                sql1 = con.createStatement();
		rs = sql1.executeQuery(s2);
                while (rs.next ()) {
                    ID = rs.getString(1);
                    Pass = rs.getString(2);
                    name = rs.getString(3);
                    user.add(new User(ID,Pass,"LECTURER",name));
		}
                sql1 = con.createStatement();
		rs = sql1.executeQuery(s3);
                while (rs.next ()) {
                    ID = rs.getString(1);
                    Pass = rs.getString(2);
                    name = rs.getString(3);
                    user.add(new User(ID,Pass,"ADMIN",name));
		}
		rs.close();
		sql1.close();
		con.close();
	} //end try
        catch (ClassNotFoundException | SQLException e) {
		System.out.println(e);
	}
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField remail;
    private javax.swing.JButton resetconfirm;
    private javax.swing.JDialog resetpass;
    private javax.swing.JPasswordField rnewPass;
    private javax.swing.JTextField ruserID;
    // End of variables declaration//GEN-END:variables

}
